package audit

//TODO logflags

import (
	"fmt"
	"log"
	"os"
	"time"
)

type iLog interface {
	Panic(s any)
	Warn(s any) (err error)
	Add(s any) (err error)
	Close(s any) (err error)
}
type Log struct {
	Path  string
	File  *os.File
	date  string
	flags int
	iLog
}

func getFFlag(flags int) (fflag int) {
	fflag = os.O_WRONLY
	if hasFlag(flags, LogFlag.FileOverwrite) {
		fflag |= os.O_TRUNC
	} else {
		fflag |= os.O_APPEND
	}
	if !hasFlag(flags, LogFlag.FileErrorNotFound) {
		fflag |= os.O_CREATE
	}
	return
}
func New(path string, flags int) (log *Log, err error) {
	if err = checkFlags(flags); err != nil {
		return
	}
	date := time.Now().Format("01-02-2006")
	log = &Log{
		flags: flags,
		date:  date,
	}
	if !hasFlag(flags, LogFlag.WriteFile) {
		log.Add("Instance Ready", LogGroup.AUDIT)
		log.Add(StringFlags(flags), LogGroup.AUDIT)
		return
	}

	// file flags
	log.Path = path
	file, err := os.OpenFile(path+date+".log", getFFlag(flags), 0644)
	if err != nil {
		return
	}
	log.File = file
	log.Add("File Ready", LogGroup.AUDIT)
	log.Add(StringFlags(flags), LogGroup.AUDIT)
	return
}

// make and assign new file on new day
func (l Log) tryMigrate(errFatal bool) (err error) {
	date := time.Now().Format("01-02-2006")
	oldDate := l.date
	if date == l.date {
		return
	}
	l.date = date
	if !(hasFlag(l.flags, LogFlag.WriteFile)) {
		return
	}
	l.Warn(fmt.Sprintf("[MIGRATING] to %s.log", date), LogGroup.AUDIT)

	file, err := os.OpenFile(l.Path+date+".log", getFFlag(l.flags)|os.O_CREATE, 0644)
	if err != nil {
		if errFatal {
			log.Fatal("Couldn't migrate file")
		}
		return
	}
	l.File = file
	l.Warn(fmt.Sprintf("[MIGRATED] autogenerated from %s.log", oldDate), LogGroup.AUDIT)
	return
}

func logFormat(s any, groups ...string) (timeNow string, output string) {
	timeNow = time.Now().Format("15:04:05")
	output = fmt.Sprintf("%v %s\n", FormatGroupings(groups...), s)
	return
}

// assumes exclusivity; mutates flags on a copy to operate
func handleError(e error, log Log, groups ...string) (err error) {
	if hasFlag(log.flags, LogFlag.ErrorIsPass) {
		return e
	}
	groups = append(groups, LogGroup.ERR)
	if hasFlag(log.flags, LogFlag.ErrorIsWarn) {
		log.flags = log.flags&LogFlag.ErrorIsWarn | LogFlag.ErrorIsPass
		log.Warn(e, groups...)
		return
	}
	log.flags = log.flags&(^LogFlag.ErrorIsPanic) | LogFlag.ErrorIsPass
	log.Panic(e, groups...)
	return
}

// will not pass errors, always writes to memory
func (l Log) Panic(s any, groups ...string) {
	l.tryMigrate(true)
	groups = append(groups, LogGroup.PANIC)
	timeNow, output := logFormat(s, groups...)
	if hasFlag(l.flags, LogFlag.WriteFile) {
		l.File.WriteString(fmt.Sprintf("%s %s", timeNow, output))
	}
	//
	log.Panic(output)
}
func (l Log) Warn(s any, groups ...string) (err error) {
	l.tryMigrate(true)
	groups = append(groups, LogGroup.WARN)
	timeNow, output := logFormat(s, groups...)
	if hasFlag(l.flags, LogFlag.WriteFile) {
		if _, err = fmt.Fprintf(l.File, "%s %s", timeNow, output); err != nil {
			return handleError(err, l)
		}
	}
	//
	if hasFlag(l.flags, LogFlag.WriteMemory) {
		log.Print(output)
	}
	return
}
func (l Log) Add(s any, groups ...string) (err error) {
	l.tryMigrate(true)
	groups = append(groups, LogGroup.LOG)
	timeNow, output := logFormat(s, groups...)
	if hasFlag(l.flags, LogFlag.WriteFile) {
		if _, err = fmt.Fprintf(l.File, "%s %s", timeNow, output); err != nil {
			return handleError(err, l)
		}
	}
	//
	if hasFlag(l.flags, LogFlag.WriteMemory) {
		log.Print(output)
	}
	return
}
