package audit

//TODO logflags

import (
	"fmt"
	"log"
	"os"
	"poll-bot/src/atomicqueue"
	"sync/atomic"
	"time"

	"github.com/google/uuid"
)

// logtype, value, groups
type queueEntry = struct {
	Type   string
	Value  any
	Groups []string
	Id     uuid.UUID
}

func newQueueEntry(t string, v any, g []string) *queueEntry {
	return &queueEntry{
		Type:   t,
		Value:  v,
		Groups: g,
		Id:     uuid.New(),
	}
}

type ErrorPromise struct {
	id    uuid.UUID
	ch    chan error
	value error
	got   bool
}

func newErrorPromise(id uuid.UUID) *ErrorPromise {
	return &ErrorPromise{
		id: id,
		ch: make(chan error, 1),
	}
}
func (p *ErrorPromise) Await() error {
	if p.got {
		return p.value
	}
	p.value = <-p.ch
	p.got = true
	return p.value
}

type iLog interface {
	Panic(s any)
	Warn(s any) (err error)
	Add(s any) (err error)
	Close(s any) (err error)
}
type Log struct {
	active       *atomic.Bool
	path         string
	file         *os.File
	promises     map[uuid.UUID]*ErrorPromise
	queue        *atomicqueue.AtomicQueue[queueEntry]
	consumerSync chan byte
	date         string
	flags        int
	iLog
}

func getFFlag(flags int) (fflag int) {
	fflag = os.O_WRONLY
	if hasFlag(flags, LogFlag.FileOverwrite) {
		fflag |= os.O_TRUNC
	} else {
		fflag |= os.O_APPEND
	}
	if !hasFlag(flags, LogFlag.FileErrorNotFound) {
		fflag |= os.O_CREATE
	}
	return
}
func (l *Log) runConsumer() {
	for {
		if !l.queue.Active() {
			break
		} else if !l.active.Load() && l.queue.Empty() {
			break
		}
		next, err := l.queue.Pop()
		if err != nil {
			continue //empty
		}
		switch next.Type {
		case LogGroup.PANIC:
			l.doPanic(next.Value, next.Groups...)
		case LogGroup.WARN:
			l.promises[next.Id].ch <- l.doWarn(next.Value, next.Groups...)
			delete(l.promises, next.Id)
		case LogGroup.LOG:
			l.promises[next.Id].ch <- l.doAdd(next.Value, next.Groups...)
			delete(l.promises, next.Id)
		}
	}
	// reaches here on a close. signifies done
	l.consumerSync <- 0
}
func New(path string, flags int, groups ...string) (log *Log, err error) {
	if err = checkFlags(flags); err != nil {
		return
	}
	date := time.Now().Format("01-02-2006")
	queue, err := atomicqueue.New[queueEntry](0, 0, atomicqueue.F_DROPFULL)
	if err != nil {
		return
	}
	active := atomic.Bool{}
	active.Store(true)
	log = &Log{
		active:       &active,
		flags:        flags,
		date:         date,
		queue:        queue,
		promises:     make(map[uuid.UUID]*ErrorPromise),
		consumerSync: make(chan byte),
	}
	go log.runConsumer()

	groups = append(groups, LogGroup.AUDIT)
	if !hasFlag(flags, LogFlag.WriteFile) {
		log.Add("Logger Instance Ready", groups...)
		log.Add(StringFlags(flags), groups...)
		return
	}

	// file flags
	log.path = path
	file, err := os.OpenFile(path+date+".log", getFFlag(flags), 0644)
	if err != nil {
		return
	}
	log.file = file
	log.Add("Logger File Ready", groups...)
	log.Add(StringFlags(flags), groups...)
	return
}

// make and assign new file on new day
func (l *Log) tryMigrate() (err error) {
	date := time.Now().Format("01-02-2006")
	oldDate := l.date
	if date == l.date {
		return
	}
	l.date = date
	if !(hasFlag(l.flags, LogFlag.WriteFile)) {
		return
	}
	l.Warn(fmt.Sprintf("[MIGRATING] to %s.log", date), LogGroup.AUDIT)

	file, err := os.OpenFile(l.path+date+".log", getFFlag(l.flags)|os.O_CREATE, 0644)
	if err != nil {
		l.Warn("Couldn't migrate file", LogGroup.AUDIT)
		return
	}
	l.file.Close()
	l.file = file
	l.Warn(fmt.Sprintf("[MIGRATED] autogenerated from %s.log", oldDate), LogGroup.AUDIT)
	return
}

func logFormat(s any, groups ...string) (timeNow string, output string) {
	timeNow = time.Now().Format("15:04:05")
	output = fmt.Sprintf("%v %s", FormatGroupings(groups...), s)
	return
}

// assumes exclusivity; mutates flags on a copy to operate
func handleError(e error, log *Log, groups ...string) (err error) {
	if hasFlag(log.flags, LogFlag.ErrorIsPass) {
		return e
	}
	groups = append(groups, LogGroup.ERR)
	if hasFlag(log.flags, LogFlag.ErrorIsWarn) {
		log.flags = log.flags&LogFlag.ErrorIsWarn | LogFlag.ErrorIsPass
		log.Warn(e, groups...)
		return
	}
	log.flags = log.flags&(^LogFlag.ErrorIsPanic) | LogFlag.ErrorIsPass
	log.Panic(e, groups...)
	return
}

func (l *Log) enqueue(group string, s any, otherGroups ...string) *ErrorPromise {
	if !l.active.Load() {
		log.Println("Log droppped: ", group, otherGroups, s)
		return newErrorPromise(uuid.Nil)
	}
	id := uuid.New()
	promise := newErrorPromise(id)
	l.promises[id] = promise
	l.queue.Push(queueEntry{
		Type:   group,
		Value:  s,
		Groups: otherGroups,
		Id:     id,
	})
	return promise
}

// will not pass errors, always writes to memory
func (l *Log) Panic(s any, groups ...string) {
	l.enqueue(LogGroup.PANIC, s, groups...)
}
func (l *Log) Warn(s any, groups ...string) ErrorPromise {
	return *l.enqueue(LogGroup.WARN, s, groups...)
}
func (l *Log) Add(s any, groups ...string) ErrorPromise {
	return *l.enqueue(LogGroup.LOG, s, groups...)
}

// should catch with log.close
func (l *Log) doPanic(s any, groups ...string) {
	l.tryMigrate()
	groups = append(groups, LogGroup.PANIC)
	timeNow, output := logFormat(s, groups...)
	if hasFlag(l.flags, LogFlag.WriteFile) {
		l.file.WriteString(fmt.Sprintf("%s %s", timeNow, output))
	}
	//
	log.Panic(output)
}
func (l *Log) doWarn(s any, groups ...string) (err error) {
	l.tryMigrate()
	groups = append(groups, LogGroup.WARN)
	timeNow, output := logFormat(s, groups...)
	if hasFlag(l.flags, LogFlag.WriteFile) {
		if _, err = fmt.Fprintf(l.file, "%s %s", timeNow, output); err != nil {
			return handleError(err, l)
		}
	}
	//
	if hasFlag(l.flags, LogFlag.WriteMemory) {
		log.Print(output)
	}
	return
}
func (l *Log) doAdd(s any, groups ...string) (err error) {
	l.tryMigrate()
	groups = append(groups, LogGroup.LOG)
	timeNow, output := logFormat(s, groups...)
	if hasFlag(l.flags, LogFlag.WriteFile) {
		if _, err = fmt.Fprintf(l.file, "%s %s", timeNow, output); err != nil {
			return handleError(err, l)
		}
	}
	//
	if hasFlag(l.flags, LogFlag.WriteMemory) {
		log.Print(output)
	}
	return
}
func (l *Log) awaitConsumerOrTimeout(ms int) (timedOut bool) {
	ok := false
	go func() {
		time.Sleep(time.Duration(ms))
		if !ok {
			timedOut = true
			l.consumerSync <- 0
		}
	}()
	<-l.consumerSync
	ok = true
	return
}
func (l *Log) Close() {
	if !l.active.Load() {
		return //idempotent
	}
	l.Add("Closing Logger\n", LogGroup.AUDIT)

	l.active.Store(false)
	if l.awaitConsumerOrTimeout(10000) {
		log.Println("Logger timed out.")
	}
	l.queue.Close()
	l.file.Close()
}
