name: lint, build, release linux binary

on:
  push:
    branches: [main]
    tags: [v*]

env:
  TARGET_PLATFORM: linux-amd64
  BIN_NAME: poll-bot-linux-amd64

jobs:
  lint:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - name: setup
        uses: actions/setup-go@v7
        with:
          go-version: '1.26.x'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12
        
  build:
    if: startsWith(github.ref, 'refs/tags/v') 

    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      
      - name: setup
        uses: actions/setup-go@v7
        with:
          go-version: "1.26.x"
        
      - name: dependencies
        run: go mod download
        
      - name: build
        env:
          GOOS: linux
          CGO_ENABLED: 0
          GOARCH: amd64
        run: go build -o ${{ env.BIN_NAME }}
      
      - name: compress
        run: tar -zcvf ${{ env.BIN_NAME }}.tar.gz ${{ env.BIN_NAME }}
      
      - name: provide build tarball
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARGET_PLATFORM }}-latest
          path: ${{ env.BIN_NAME }}.tar.gz
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-slim

    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v7

      - name: download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.TARGET_PLATFORM }}-latest
          path: ${{ env.TARGET_PLATFORM }}
        
      - name: make release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ env.TARGET_PLATFORM }} autorelease
          prerelease: true
          files: ${{env.TARGET_PLATFORM}}/${{ env.BIN_NAME }}*